name: wbt
channels:
- conda-forge
- nodefaults
dependencies:
- python >=3.11

- pywbt >=0.2.0

# Deps for examples
- folium
- geopandas-base >=1
- ipykernel
- ipywidgets
- mapclassify
- matplotlib-base
- planetary-computer
- pyogrio
- pystac-client
- rasterio
- rioxarray
- shapely >=2
