site_name: PyWBT
site_url: https://cheginit.github.io/pywbt

theme:
  name: material
  custom_dir: docs/overrides
  favicon: assets/pywbt.png
  logo: assets/pywbt.png
  site_url: https://cheginit.github.io/pywbt
  font:
    text: Red Hat Text
    code: JetBrains Mono

  palette:
    # Palette toggle for automatic mode
  - media: (prefers-color-scheme)
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode

    # Palette toggle for light mode
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: prefix-light
    accent: prefix-light
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

    # Palette toggle for dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: prefix
    accent: prefix
    toggle:
      icon: material/brightness-4
      name: Switch to system preference

  icon:
    edit: material/pencil
    view: material/eye

  features:
  - content.tabs.link
  - content.code.copy
  - content.action.edit
  - content.code.annotate
    # - content.code.select Sponsor only
  - navigation.instant
  - navigation.instant.progress
  - navigation.tracking
  - navigation.sections
  - navigation.top
  - navigation.footer

extra_css:
- stylesheets/extra.css

repo_url: https://github.com/cheginit/pywbt/
edit_uri: edit/main/docs/

markdown_extensions:
- admonition
- def_list
- footnotes
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.details
- pymdownx.superfences
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
- pymdownx.tabbed:
    alternate_style: true
- toc:
    toc_depth: 3
    permalink: '#'
- mdx_truly_sane_lists

extra:
  homepage: https://cheginit.github.io
  social:
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/_taher_
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/tchegini
  - icon: fontawesome/brands/github
    link: https://github.com/cheginit
  version:
    provider: mike

nav:
- Getting Started: index.md
- Release Notes: CHANGELOG.md
- Examples:
  - Delineat Basin: examples/basin.ipynb
- API Reference: reference.md
plugins:
- mkdocs-jupyter:
    include: ['*.ipynb']
    include_source: true
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        paths: [src]
        options:
          docstring_style: numpy
          inherited_members: true
          members_order: source
          separate_signature: true
          unwrap_annotated: false
          filters:
          - '!^_'
          merge_init_into_class: true
          docstring_section_style: list
          signature_crossrefs: true
          show_source: false
hooks:
- docs/docs_hooks.py

  # - search
  # - social
  # - mike:
    # These fields are all optional; the defaults are as below...
    # alias_type: symlink
    # redirect_template: null
    # deploy_prefix: ''
    # canonical_version: null
    # version_selector: true
    # css_dir: css
    # javascript_dir: js
